steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "Googles_Cloud_URl_XXXXXXXX-docker.pkg.dev/project-name/registry/products-ms",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "Googles_Cloud_URl_XXXXXXXX-docker.pkg.dev/project-name/registry/products-ms",
      ]